AllCops:
  Exclude:
    - 'test/dummy/*'
    - 'test/dummy/*/*'
    - 'test/dummy/*/*/*'
Layout/LineLength:
  Max: 120
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/Documentation:
  Enabled: false
