AllCops:
  Exclude:
    - 'test/dummy/*'
    - 'test/dummy/*/*'
    - 'test/dummy/*/*/*'

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Documentation:
  Enabled: false
